### ISSUE TITLE
Checklist for 1.06

### ISSUE THREAD

**Issue by WombatFromHell** [WombatFromHell/OriginSteamOverlayLauncher#10]
- [x] Add 'ReLaunch' option to stop OSOL from closing a pre-existing launcher before launching a game
- [x] Add 'DoNotClose' option to stop OSOL from closing a launcher after quitting a game
- [x] Implement a mutex to stop obnoxious behavior in rare circumstances
- [x] Expose more timeout options in the INI
- [x] Add an INI command overview dialog when launching with "/help"
- [x] Fix OSOL not launching Battle.net URIs properly in URI mode
- [x] Look into implementing an optional auto-minimize upon detection of launcher
- [x] Allow renaming OSOL executable (pick up non-hardcoded OSOL ini/log files)
- [ ] ~~Improve process handling when launcher/game cannot launch~~
- [ ] ~~Investigate process detection desync (inability to detect PID in some cases?)~~
- [ ] ~~Look into improving the management of OSOL INI files for different games (mediating pre-launcher?)~~ (Delayed to v1.07a)
- [ ] ~~Explore implementing GloSC integration~~ (Delayed to v1.07a)

**Comment by BarterClub** [comment]
Could be get a minimize launcher when game is launched?

**Comment by WombatFromHell** [comment]
Possible, but annoying to get working across all launchers. No guarantees.

**Comment by WombatFromHell** [comment]
I'm not having much luck tracking down why Battlefront 2 won't launch when called with the game -> launcher proxy. Still investigating process detection desync, not much progress on it so far though.

**Comment by SubSonix** [comment]
@WombatFromHell Battlefront 2 (2017) works fine for me. It does cause the game to crash a bit faster than usual though (pretty sure the game has a memory leak, may just be me though. I doubt it's directly related)

**Comment by WombatFromHell** [comment]
I misspoke. I was referring to issue #9 where OSOL desyncs when looking for the active game process resulting in losing the game PID and not closing the launcher after the game exits. This is most likely caused by the Origin launcher proxy embedded in the game executable that calls home to Origin to authenticate so the Origin client can bring up the game inside the launcher.

Due to the fact that I don't have the  game I'm having to test for the bug in a simulated environment (using a dummy executable) to try and duplicate it to no avail. This issue is a blocker for v1.06 unless I can clarify that it isn't on my end within a reasonable timeframe.
