### ISSUE TITLE
Checklist for v1.07

### ISSUE THREAD

**Issue by WombatFromHell** [WombatFromHell/OriginSteamOverlayLauncher#14]
- [x] Refresh system tray icons after closing the launcher PID
- [ ] Implement mediating pre-launcher GUI for better INI management (in progress - will require test branch -> v1.08)
- [ ] ~~Explore implementing GloSC integration (auto-adding GloSC/Steam shortcuts)~~ (low priority atm)
- [x] Change ```ProcessLauncher()``` to support tracking process trees so the user can track any set of executables - not just launchers (useful for Cemu + SC Gyro util)
- [x] Implement copying command lines from a pre-existing launcher/game to OSOL to improve support for third-party launchers (Escape from Tarkov, some MMORPGs)
- [x] Try to improve ```MinimizeLauncher``` behavior when exiting Origin games
- [x] Implement option to not elevate external pre-post processes
- [x] Enable DPI awareness for non-blurry rendering on HiDPI screens
- [x] Add ```ForceLauncher``` option for use with ```CommandlineProxy``` for games that require the launcher to run in the background (Star Citizen, et al)
- [x] ```PreGameLauncherWaitTime``` will now work in both ```LauncherMode=Normal``` and ```LauncherMode=URI```
- [x] Implement an option to terminate OSOL after launching a game
- [x] Implement setting CPU affinity for the game process
- [x] Implement setting Process Priority for the game process

ETA: In a few days...

**Comment by WombatFromHell** [comment]
I'm marking GLoSC integration as wontfix due to lack of time to implement (would require implementing some hooking and better debugging). I may put it back on the todo list in the future.

The INI manager (mediating pre-launcher) is still in private testing.

**Comment by WombatFromHell** [comment]
```CommandlineProxy``` support is being very difficult to debug without a proper testing environment so I'm marking it as a blocker for v1.07. I'll take the next few days to sort this out and hopefully get a solution together.

**Comment by WombatFromHell** [comment]
Just a status update: it's likely I'll have to release v1.07 without the INI manager completed. I've changed the status on GloSC integration to low priority, as I may have time in the next few months to work implement something along those lines into the INI manager UI.

**Comment by WombatFromHell** [comment]
After an unintended hiatus from OSOL I've come back to finish implementing features for release in v1.07. No specific release date at this time, but I'm targetting sometime in the next 2 or 3 weeks.

**Comment by SubSonix** [comment]
Welcome back, I hope all is well :)

**Comment by WombatFromHell** [comment]
OSOL v1.07 is finally done (knock on wood). Many apologies for the unintentionally long wait. Work and side projects got the better of me. I'll be moving most of my effort, aside from bug-fixing, toward a new branch so I can finish implementing the pre-launcher/INI manager.
