### ISSUE TITLE
Checklist for v1.08

### ISSUE THREAD

**Issue by WombatFromHell** [WombatFromHell/OriginSteamOverlayLauncher#26]
- [x] Investigate GOG launcher misbehaving sometimes
- [x] Implement workaround for processes that lack a MainWindowHandle or MainWindowTitle
- [x] Fix URI mode behavior for newer Origin/EGL/Uplay games
- [x] More code cleanup for better readability
- [x] First pass at implementing unit tests for testable methods and classes
- [x] Implement better monitoring for both launcher and game processes
- [x] Migrate to a development staging branch for safer git deployment
- [x] Re-factor process detection to be less brittle when launchers update themselves
- [ ] ~~Implement mediating pre-launcher GUI for better INI management (postponed)~~
- [ ] ~~Investigate implementing hot-launching of native Steam games using OSOL~~
- [x] Implement `SkipLauncher` for games that relaunch themselves via third-party launcher when called by Steam
- [x] Implement better behavior for Battle.net (game launch commands)
- [x] Fix broken LauncherURI code wrt Battle.net and friends
- [x] Fix broken CommandlineProxy when detecting unix-style paths (e.g. UE4/UE3 engine)
- [x] Deprecate `SendEnterToLauncher` INI option (workaround)
- [x] Improve MainWindowHandle/ModuleHandle detection (Cemu SC Gyro/Electron workaround)

ETA: When it's done!

**Comment by WombatFromHell** [comment]
Turns out there's no need to add any additional features for hot-launching/hot-renaming of Steam game executables. If you use the Steam URI protocol (via `LauncherMode=URI`) to run the games you can simply tack your game arguments onto that and Steam will oblige. Creating a non-Steam game shortcut is, unfortunately, necessary though.

**Comment by WombatFromHell** [comment]
Status update: v1.08 is nearing completion, the only thing I have left to do is to implement a better method of tracking what the launcher and game processes are doing so that OSOL gets confused less when a game wants to restart itself or when the launcher wants to auto-update before the game is launched.
