### ISSUE TITLE
Task list for v1.09

### ISSUE THREAD

**Issue by WombatFromHell** [WombatFromHell/OriginSteamOverlayLauncher#42]
- [x] Massive process detection and monitoring rewrite (is now properly asynchronous).
- [x] Refactored INI handling for better maintainability.
- [x] Replaced `ForceLauncher` with `AutoGameLaunch` option and fixed bugs.
- [x] Deprecated `TerminateOSOLUponLaunch` option (made obsolete by `AutoGameLaunch`).
- [x] Some minor improvements for EGS detection and handling.
- [x] Implemented `PreGameWaitTime` option for delaying game launch.
- [x] Deprecated `CommandlineProxy` feature (how many people even used this?)
- [x] Adjusted timeouts for new asynchronous launching/monitoring.
- [x] Deprecated `LauncherMode`, OSOL will now automatically use `LauncherURI` for setting its mode.
- [x] Implemented parent/child process tracking and validation.
- [x] Implemented config migration from old to new version.
- [x] Bug testing and unit tests to cover refactored code.
- [x] Fix non-traditional launching/monitoring behavior (for Steam mostly).
- [x] Fix EGL launching behavior when using `LauncherURI` mode.

**Comment by WombatFromHell** [comment]
I'm nearing completion on the new asynchronous event-based process detection and monitoring system going into v1.09. These changes will need lots of testing so I'll likely make a pre-release test build in the next few days depending on how much time I have.

**Comment by WombatFromHell** [comment]
I've gotten sidetracked with refactoring of the config file handling code. It's in dire need of an overhaul. I'm still testing the process detection and monitoring system.

**Comment by WombatFromHell** [comment]
Rewrite is 99% done. Just need to write unit tests and squash some async bugs in `LaunchLogic` before I push out a pre-release beta.

**Comment by WombatFromHell** [comment]
I'll be testing an experimental process tracking system for v1.10. I thought I would have time to implement and test it over the weekend, but this is not going to be the case. I'll finish up writing unit tests for the new config handling code and push a pre-release.

**Comment by WombatFromHell** [comment]
Change of plans. It looks like I need to implement child process tracking in order to solve issues with Diablo 3 and EGL games. I'll also be adding automatic config migration to prevent loss of data for pre v1.09 configs.

**Comment by WombatFromHell** [comment]
Tracking of process (grand)children is in, now just "legacy" (pre v1.09) config migration left to go. I'll probably constrain this migration to existing Path/Arg variables. The new timeouts in v1.09 generally give a better experience for most users, so overriding them makes sense I think.

**Comment by WombatFromHell** [comment]
Both sets of non-standard launching bugs should be fixed in build v1.09c. I've tested against: Diablo 3 (Battle.net), Dauntless (EGL), Apex Legends, and AC: Odyssey (Steam -> UPlay). All check out. I'm just running through some final tests before I push the next build.

**Comment by WombatFromHell** [comment]
I'll give v1.09f a few more days of testing in pre-release before I move it to a full release build. I'll go ahead and close this task ticket now since I'm not aware of any blockers before release.
