### ISSUE TITLE
Task list for 1.10

### ISSUE THREAD

**Issue by WombatFromHell** [WombatFromHell/OriginSteamOverlayLauncher#45]
- [ ] Implement smarter launcher monitoring to better detect when updates are happening
- [ ] Implement an optional dialog overlay to inform the user of what OSOL is doing before a game is launched
- [ ] Implement a system tray icon and context menu so the user can forcefully quit OSOL if they choose

ETA: TBD
